local disabled_filetypes = {
    "NvimTree",
    "TelescopePrompt",
    "aerial",
    "alpha",
    "checkhealth",
    "dapui*",
    "Diffview*",
    "Dressing*",
    "help",
    "httpResult",
    "lazy",
    "lspinfo",
    "Neogit*",
    "mason",
    "neotest%-summary",
    "minifiles",
    "neo%-tree*",
    "netrw",
    "noice",
    "notify",
    "prompt",
    "qf",
    "query",
    "oil",
    "undotree",
    "trouble",
    "Trouble",
    "fugitive",
}

return disabled_filetypes
