#!/bin/bash
#MISE description="Delete patch branch"
#MISE alias=["delete-branch","deleb"]

mise tasks run clean
mise tasks run git:switch-master
git branch --list "patch*" | xargs -n 1 git branch -D

# vim:ft=bash
