#!/bin/bash
# mise description="workday morning routine"
# mise alias="morning-routine"

mise tasks run git:fetch:clean-fetch
mise tasks run git:delete-branch
mise tasks run git:pull
mise tasks run patch:branch

# vim:ft=bash
