#!/bin/bash
# mise description="Add commit message up to `origin/master` to CHANGELOG.md"

host_name=$(cat /etc/hostname)

case "$host_name" in
    "Wakamo" | "Izuna" | "azusa")
        echo "Pushing to origin..."
        git fetch origin
        git push origin master
        git push origin --tags
        echo "Pushing to codeberg..."
        git fetch codeberg
        git push codeberg master
        git push codeberg --tags
        ;;
    *)
        echo "        THIS IS WORK-PC!!!        "
        echo "DON'T PUSH TO REMOTE REPOSITORY!!!"
        ;;
esac

# vim:ft=bash
