#!/bin/bash
#MISE description="Run update"
#MISE depends=["clean"]

host_name=$(cat /etc/hostname)

# fish
cp ~/.config/fish/completions/* ./dot_config/fish/completions/
#cp ~/.config/fish/fish_plugins ./dot_config/fish/fish_plugins
cp ~/.config/fish/pez.toml ./dot_config/fish/pez.toml
cp ~/.config/fish/pez-lock.toml ./dot_config/fish/pez-lock.toml

# yazi-fm
chezmoi add ~/.config/yazi/keymap.toml
chezmoi add ~/.config/yazi/yazi.toml
chezmoi add ~/.config/yazi/theme.toml
chezmoi add ~/.config/yazi/package.toml
chezmoi add ~/.config/yazi/init.lua
tombi format dot_config/yazi/*.toml

#MISE
chezmoi add ~/.config/mise/config.toml

# bob
chezmoi add ~/.bob-version

# mimikun package lists
chezmoi add ~/.mimikun-pkglists/*.txt

# Brewfile
if [[ "$(uname)" == "Darwin" ]]; then
    chezmoi add ~/Brewfile
fi

# go packages (managed by gup)
chezmoi add ~/.config/gup/gup.conf

# managed by aqua
chezmoi add ~/.config/aqua/aqua/aqua.yaml
chezmoi add ~/.config/aqua/aqua/other.yaml
chezmoi add ~/.config/aqua/aqua/custom.yaml
chezmoi add ~/.config/aqua/aqua.yaml
chezmoi add ~/.config/aqua/policy.yaml
chezmoi add ~/.config/aqua/registries/go-install.yaml
chezmoi add ~/.config/aqua/registries/github-release.yaml

# neovim lockfiles
chezmoi add ~/.config/nvim/lazy-lock.json
chezmoi add ~/.config/nvim/mason-lock.json
chezmoi add ~/.config/nvim/dotfyle.json
deno fmt dot_config/nvim/dotfyle.json

# sunbeam
chezmoi add ~/.config/sunbeam/sunbeam.json

# brow6el configs
chezmoi add ~/.brow6el/bookmarks
chezmoi add ~/.brow6el/userscripts
chezmoi add ~/.brow6el/browser.conf
chezmoi add ~/.brow6el/cef_flags.conf
chezmoi add ~/.brow6el/userscripts.conf

# ~/.local/bin/*
chezmoi add ~/.local/bin/chezmoi_post_apply_hook
chezmoi add ~/.local/bin/chezmoi_pre_apply_hook
chezmoi add ~/.local/bin/cpat
chezmoi add ~/.local/bin/editorconfig
chezmoi add ~/.local/bin/generate_cargo_package_list
chezmoi add ~/.local/bin/generate_pip_package_list
chezmoi add ~/.local/bin/generate_pipx_package_list
chezmoi add ~/.local/bin/install_cargo_packages
chezmoi add ~/.local/bin/install_gh_extensions
chezmoi add ~/.local/bin/install_pip_packages
chezmoi add ~/.local/bin/install_pipx_packages
chezmoi add ~/.local/bin/lk
chezmoi add ~/.local/bin/numeronym
chezmoi add ~/.local/bin/pcd
chezmoi add ~/.local/bin/pueue_update_cargo_packages
chezmoi add ~/.local/bin/pueue_update_pip_packages
chezmoi add ~/.local/bin/re_boot
chezmoi add ~/.local/bin/read_confirm
chezmoi add ~/.local/bin/shut_down
chezmoi add ~/.local/bin/update_cargo_packages
chezmoi add ~/.local/bin/update_chromedriver
chezmoi add ~/.local/bin/update_docker_compose
chezmoi add ~/.local/bin/update_fish_completions
chezmoi add ~/.local/bin/update_geckodriver
chezmoi add ~/.local/bin/update_mise
chezmoi add ~/.local/bin/update_pip_packages
chezmoi add ~/.local/bin/update_pnpm
chezmoi add ~/.local/bin/update_poetry
chezmoi add ~/.local/bin/update_twitch_cli
chezmoi add ~/.local/bin/vup
chezmoi add ~/.local/bin/wsl-open

# ArchLinux configs
# HOSTNAME = azusa ONLY
if [ "$host_name" = "azusa" ]; then
    chezmoi add ~/.config/i3/config
    chezmoi add ~/.config/i3status-rust/config.toml
    chezmoi add ~/.config/fcitx5/config
    chezmoi add ~/.config/betterlockscreen/betterlockscreenrc
    chezmoi add ~/.config/polybar/config.ini
    #chezmoi add ~/.config/rofi/config.rasi
    chezmoi add ~/.config/flameshot/flameshot.ini

    chezmoi add ~/.xinitrc
    chezmoi add ~/.xmodmap
    chezmoi add ~/.Xresources
fi

# vim:ft=bash
