---@type GrugFarOptions
local opts = {
    maxWorkers = require("config.global").is_human_rights and 4 or 1,
    resultsSeparatorLineChar = "",
    spinnerStates = {
        "󱑋 ",
        "󱑌 ",
        "󱑍 ",
        "󱑎 ",
        "󱑏 ",
        "󱑐 ",
        "󱑑 ",
        "󱑒 ",
        "󱑓 ",
        "󱑔 ",
        "󱑕 ",
        "󱑖 ",
    },
    icons = {
        enabled = true,
        fileIconsProvider = "first_available",
        actionEntryBullet = " ",
        searchInput = " ",
        replaceInput = " ",
        filesFilterInput = " ",
        flagsInput = "󰮚 ",
        pathsInput = " ",
        resultsStatusReady = "󱩾 ",
        resultsStatusError = " ",
        resultsStatusSuccess = "󰗡 ",
        resultsActionMessage = "  ",
        resultsEngineLeft = "⟪",
        resultsEngineRight = "⟫",
        resultsChangeIndicator = "┃",
        resultsAddedIndicator = "▒",
        resultsRemovedIndicator = "▒",
        resultsDiffSeparatorIndicator = "┊",
        historyTitle = "   ",
        helpTitle = " 󰘥  ",
        newline = " ",
    },
}

return opts
