bg = "#EBDBB2"
fg = "#644855"
bar_bg = "#83A598"
signcol_fg = "#458488"
minibuffer_hl = "#8fafa2"

[syntax]
default = { }
dot = { bg = "#D5C4A1" }
load = { bg = "#957FB8" }
exec = { bg = "#Bf616A" }

boolean = { fg = "#DCA561", bold = true }
character = { fg = "#347e73", italic = true }
comment = { fg = "#9b8391", italic = true }
constant = { fg = "#ce752c" }
function = { fg = "#4685c0" }
"function.macro" = { fg = "#ce752c" }
keyword = { fg = "#a44860" }
module = { fg = "#726a98" }
number = { fg = "#D27E99" }
operator = { fg = "#ad6693" }
punctuation = { fg = "#754e85" }
string = { fg = "#347e73" }
type = { fg = "#0f8a97" }
variable = { }

"markup.italic" = { italic = true } 
"markup.bold" = { bold = true } 
"markup.heading" = { fg = "#8793B5", bold = true }
"markup.raw" = { fg = "#624354", italic = true }
"markup.quote" = { fg = "#957FB8", italic = true }
"markup.link.url" = { fg = "#9CABCA", underline = true }
"markup.link.label" = { fg = "#2D4F67", bold = true }
"markup.list.unchecked" = { fg = "#DCA561", bold = true }
"markup.list.checked" = { fg = "#9AB292", bold = true }
"markup.list" = { fg = "#9CABCA", bold = true } 

label = { fg = "#E6C384" }
