fg = "fg"
bg = "bg"
bar_bg = "#4E415C"
signcol_fg = "#544863"
minibuffer_hl = "#3E3549"

[palette]
fg = "#E6D29E"
bg = "#1B1720"
blue = "#8793B5"
brown = "#624354"
dark-blue = "#2D4F67"
dark-yellow = "#DCA561"
light-blue = "#9CABCA"
light-red = "#D27E99"
mint = "#61DCA5"
orange = "#FFA066"
purple = "#957FB8"
sage = "#9AB292"
salmon = "#Bf616A"
sea-blue = "#336677"
yellow = "#E6C384"

[syntax]
default = { fg = "fg", bg = "bg" }
dot = { bg = "sea-blue" }
load = { bg = "purple" }
exec = { bg = "salmon" }

boolean = { fg = "dark-yellow", bold = true }
character = { fg = "mint", italic = true }
comment = { fg = "brown", italic = true }
constant = { fg = "orange" }
function = { fg = "blue" }
"function.macro" = { fg = "orange" }
keyword = { fg = "salmon" }
module = { fg = "dark-blue" }
number = { fg = "light-red" }
operator = { fg = "dark-yellow" }
punctuation = { fg = "light-blue" }
string = { fg = "mint" }
type = { fg = "sage" }
variable = { }

"markup.italic" = { italic = true } 
"markup.bold" = { bold = true } 
"markup.heading" = { fg = "blue", bold = true }
"markup.raw" = { fg = "brown", italic = true }
"markup.quote" = { fg = "purple", italic = true }
"markup.link.url" = { fg = "light-blue", underline = true }
"markup.link.label" = { fg = "dark-blue", bold = true }
"markup.list.unchecked" = { fg = "dark-yellow", bold = true }
"markup.list.checked" = { fg = "sage", bold = true }
"markup.list" = { fg = "light-blue", bold = true } 

label = { fg = "yellow" }
