[tools]
# NOTE: single
"asdf:mise-plugins/mise-dotnet" = "latest"
erlang = "latest"
go = "latest"
lua = "5.1"
pkl = "latest"
ruby = "latest"
"github:mozilla/geckodriver" = "latest"

# NOTE: multi
node = [
  "lts",
  "22",
  "latest",
  "23",
]
python = [
  "latest",
  "3.14",
  "3.12",
  "3",
  "3.13",
]
vim = [
  "ref:master",
  "latest",
]
zig = [
  "master",
  "latest",
]

[tools."http:chromedriver"]
version = "latest"
version_list_url = "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE"

[tools."http:chromedriver".platforms]
linux-x64 = { url = "https://storage.googleapis.com/chrome-for-testing-public/{{version}}/linux64/chromedriver-linux64.zip" }

[settings]
activate_aggressive = true
auto_install = true
exec_auto_install = true
experimental = true
idiomatic_version_file_enable_tools = [
  "crystal",
  "elixir",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "terraform",
  "yarn",
]
jobs = 1
lockfile = true
not_found_auto_install = true
cargo.binstall = false
npm.bun = true
pipx.uvx = true
status.missing_tools = "if_other_versions_installed"
