# @generated by usage-cli from usage spec

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in aube." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"
set -l spec_file "$spec_dir/usage__usage_spec_aube_1_38_1.spec"
if not test -f "$spec_file"
    find "$spec_dir" -maxdepth 1 -name 'usage__usage_spec_aube_*.spec' -type f -mtime +30 -delete 2>/dev/null
    aube usage | string collect > "$spec_file"
end

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc aube -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc aube -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
# @generated by usage-cli from stdin

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in aubr." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_aubr 'name aubr
bin aubr
version "1.38.1"
about "Run a script defined in package.json"
flag "-C --dir --cd --prefix" help="Change to directory before running (like `make -C` or `mise --cd`)" global=#true {
    arg <DIR>
}
flag "-F --filter" help="Scope command execution to workspace packages matching PATTERN" var=#true global=#true {
    long_help #"""
Scope command execution to workspace packages matching PATTERN.

Supports exact names (`my-pkg`), globs (`@scope/*`, `*-plugin`), paths (`./packages/api`), graph selectors (`pkg...`, `...pkg`), git-ref selectors (`[origin/main]`), and exclusions (`!pkg`). Repeatable; matches are OR-ed.

Currently honored by `run`, `test`, `start`, `stop`, `restart`, `install`, `exec`, `list`, `publish`, `deploy`, `add`, `remove`, `update`, `why`, and implicit-script invocations.
"""#
    arg <WORKSPACE>
}
flag "-r --recursive" help="Run the command across every workspace package" global=#true {
    long_help #"""
Run the command across every workspace package.

Equivalent to `--filter=*`; if `--filter` is also given, `--recursive` is a no-op and the explicit filter wins. Honored by the same commands as `--filter`.
"""#
}
flag "-v --verbose" help="Enable verbose/debug logging (shortcut for `--loglevel debug`)" global=#true
flag "-V --version" help="Print version and check for updates" global=#true {
    long_help #"""
Print version and check for updates.

Manual flag so we can run the async update notifier alongside the version print — clap\'s auto `Action::Version` exits inside `parse_from`, before the tokio runtime is built.
"""#
}
flag --aggregate-output help="Group workspace command output after each package finishes" hide=#true global=#true {
    long_help #"""
Group workspace command output after each package finishes.

Accepted for pnpm compatibility; aube\'s workspace fanout is currently sequential, so output is already grouped.
"""#
}
flag --color help="Force colored output even when stderr is not a TTY" global=#true {
    long_help #"""
Force colored output even when stderr is not a TTY.

Overrides `NO_COLOR` / `CLICOLOR=0`. Mutually exclusive with `--no-color`.
"""#
}
flag --diag help="Enable cold-install deep diagnostics. Modes: summary  — sum_ms / mean / max / %wall table at end trace    — summary + critical path + starvation + what-if + lifecycle live     — like trace, plus print every span >= 100ms to stderr live full     — like trace, plus write JSONL trace to a file (defaults to ./aube-diag.jsonl)" global=#true {
    long_help #"""
Enable cold-install deep diagnostics. Modes: summary  — sum_ms / mean / max / %wall table at end trace    — summary + critical path + starvation + what-if + lifecycle live     — like trace, plus print every span >= 100ms to stderr live full     — like trace, plus write JSONL trace to a file (defaults to ./aube-diag.jsonl)

Quick form: `--diag` with no value defaults to `trace`. Output file path can be set via `--diag-file`. Threshold for live mode via `--diag-threshold-ms`.
"""#
    arg <MODE>
}
flag --diag-file help="Path for `--diag full` JSONL trace (default: ./aube-diag.jsonl)" global=#true {
    arg <PATH>
}
flag --diag-threshold-ms help="Live-mode threshold: only print spans whose duration is >= N ms (default 100)" global=#true {
    arg <MS>
}
flag --fail-if-no-match help="Error when a workspace selector matches no packages" global=#true {
    long_help #"""
Error when a workspace selector matches no packages.

Accepted globally; selected commands already fail on empty matches.
"""#
}
flag --filter-prod help="Production-only variant of `--filter`" var=#true global=#true {
    long_help #"""
Production-only variant of `--filter`.

Same selector grammar as `--filter`, but graph walks (`pkg...`, `...pkg`) only follow `dependencies` / `optionalDependencies` / `peerDependencies` edges — `devDependencies` (and packages reachable solely through them) are skipped. Non-graph forms (exact name, glob, path, `[git-ref]`) behave identically to `--filter`. Repeatable; can be combined with `--filter`.
"""#
    arg <PATTERN>
}
flag --ignore-workspace help="Ignore workspace discovery for commands that support workspace fanout" hide=#true global=#true {
    long_help #"""
Ignore workspace discovery for commands that support workspace fanout.

Parsed for pnpm compatibility.
"""#
}
flag --include-workspace-root help="Include the workspace root in recursive workspace operations" hide=#true global=#true {
    long_help #"""
Include the workspace root in recursive workspace operations.

Parsed for pnpm compatibility.
"""#
}
flag --loglevel help="Set the log level. Logs at or above this level are shown" global=#true {
    arg <LEVEL> {
        choices trace debug info warn error silent
    }
}
flag --no-color help="Disable colored output" global=#true {
    long_help #"""
Disable colored output.

Overrides `FORCE_COLOR` / `CLICOLOR_FORCE` and sets `NO_COLOR=1` so downstream libraries (miette, clx, child processes) all see the same choice.
"""#
}
flag --reporter help="Output format: default, append-only, ndjson, silent" global=#true {
    long_help #"""
Output format: default, append-only, ndjson, silent.

`default` renders the progress UI when stderr is a TTY; `append-only` disables the progress UI in favor of plain line-at-a-time logs; `ndjson` swaps the tracing fmt layer for the JSON formatter (one JSON object per log event on stderr) and is what tooling wrappers should consume; `silent` suppresses all non-error output (alias for `--loglevel silent`).
"""#
    arg <NAME> {
        choices default append-only ndjson silent
    }
}
flag --silent help="Suppress all non-error output (alias for `--loglevel silent`)" global=#true
flag --stream help="Stream workspace command output as each child process writes it" hide=#true global=#true {
    long_help #"""
Stream workspace command output as each child process writes it.

Accepted for pnpm compatibility; aube\'s workspace fanout is currently sequential.
"""#
}
flag --use-stderr help="Route lifecycle and workspace command output through stderr" hide=#true global=#true {
    long_help #"""
Route lifecycle and workspace command output through stderr.

Accepted for pnpm compatibility.
"""#
}
flag --workspace-packages help="Prefer workspace packages when resolving dependencies" hide=#true global=#true {
    long_help #"""
Prefer workspace packages when resolving dependencies.

Parsed for pnpm compatibility; aube already resolves workspace packages when a workspace is present.
"""#
}
flag --workspace-root help="Run from the workspace root regardless of the current package" global=#true
flag "-y --yes" help="Automatically answer yes to prompts" hide=#true global=#true {
    long_help #"""
Automatically answer yes to prompts.

Parsed for pnpm compatibility; aube does not currently prompt on these paths.
"""#
}
flag --complete help="Print the nearest `package.json`\'s scripts for shell completion" hide=#true {
    long_help #"""
Print the nearest `package.json`\'s scripts for shell completion.

Consumed by the `complete "script"` node in the usage spec, not meant to be typed by hand.
"""#
}
flag --if-present help="Don\'t error if the script is missing from package.json"
flag --inspect help="Forward `--inspect` to a Node-backed script or local binary" {
    arg "[[HOST:]PORT]" required=#false
}
flag --inspect-brk help="Forward `--inspect-brk` to a Node-backed script or local binary" {
    arg "[[HOST:]PORT]" required=#false
}
flag --no-bail help="Continue recursive execution after a script fails" {
    long_help #"""
Continue recursive execution after a script fails.

Parsed for pnpm compatibility; aube\'s sequential fanout still stops on first failure.
"""#
}
flag --no-install help="Skip auto-install check"
flag --no-sort help="Disable topological sorting (default is on)" {
    long_help #"""
Disable topological sorting (default is on).

Without this, recursive runs visit packages in a deps-first order so a `build` script in a shared library finishes before a dependent app\'s `build` starts. Pass this to fall back to the raw workspace-listing order.
"""#
}
flag --parallel help="Run the script in every matched workspace package concurrently" {
    long_help #"""
Run the script in every matched workspace package concurrently.

Unbounded parallelism. Pair with `--workspace-concurrency=N` to cap the worker count. Single-package runs ignore this flag. First non-zero exit fails the whole run, but siblings are allowed to finish so their output isn\'t truncated. Child stdio is piped and lines are emitted with a `<package>: ` prefix; pass `--reporter-hide-prefix` to drop the labels.
"""#
}
flag --report-summary help="Write a recursive run summary file" {
    long_help #"""
Write a recursive run summary file.

Parsed for pnpm compatibility.
"""#
}
flag --reporter-hide-prefix help="Hide the `<package>: ` label on parallel-run output lines" {
    long_help #"""
Hide the `<package>: ` label on parallel-run output lines.

Lines are still piped through aube (so the line breaks are clean even when many packages run at once), but the source package isn\'t named on each line. Sequential runs ignore this flag.
"""#
}
flag --resume-from help="Resume recursive execution starting at this package name" {
    long_help #"""
Resume recursive execution starting at this package name.

After the topo sort and `--reverse` are applied, packages before the named one in the resulting order are skipped. Errors if the name isn\'t in the matched workspace set.
"""#
    arg <PACKAGE>
}
flag --reverse help="Reverse the recursive execution order (after topo sort)" {
    long_help #"""
Reverse the recursive execution order (after topo sort).

Useful for teardown-style scripts where dependents must shut down before their deps.
"""#
}
flag --sort help="Sort recursive packages topologically (this is the default)" {
    long_help #"""
Sort recursive packages topologically (this is the default).

Pass to override an earlier `--no-sort` on the same invocation.
"""#
}
flag -s help="Suppress aube\'s wrapper output while still showing script stdout/stderr" {
    long_help #"""
Suppress aube\'s wrapper output while still showing script stdout/stderr.

Short alias for the global `--silent` flag; long form is intentionally omitted to avoid shadowing the global `--silent` in clap\'s dispatch.
"""#
}
flag --workspace-concurrency help="Cap the number of recursive packages running at once" {
    long_help #"""
Cap the number of recursive packages running at once.

Setting this implicitly enables parallel mode at width `N`. `0` means "use the available CPU count". Without this flag, `--parallel` stays unbounded.
"""#
    arg <N>
}
flag --frozen-lockfile help="Error if the lockfile drifts from package.json"
flag --no-frozen-lockfile help="Always re-resolve, even if the lockfile is up to date"
flag --prefer-frozen-lockfile help="Use the lockfile when fresh, re-resolve when stale"
flag --fetch-retries help="Number of retry attempts for failed registry fetches" {
    long_help #"""
Number of retry attempts for failed registry fetches.

Overrides `fetchRetries` / `fetch-retries` from `.npmrc` / `aube-workspace.yaml` when set. Pair with `--fetch-timeout` to fail fast in scripted test runs.
"""#
    arg <N>
}
flag --fetch-retry-factor help="Exponential backoff factor between retry attempts" {
    long_help #"""
Exponential backoff factor between retry attempts.

Overrides `fetchRetryFactor` / `fetch-retry-factor` from `.npmrc` / `aube-workspace.yaml` when set. Integer-only — the underlying `FetchPolicy.retry_factor` is `u32`. Fractional values like `1.5` are rejected by clap.
"""#
    arg <N>
}
flag --fetch-retry-maxtimeout help="Upper bound (ms) on the computed retry backoff" {
    long_help #"""
Upper bound (ms) on the computed retry backoff.

Overrides `fetchRetryMaxtimeout` / `fetch-retry-maxtimeout` from `.npmrc` / `aube-workspace.yaml` when set.
"""#
    arg <MS>
}
flag --fetch-retry-mintimeout help="Lower bound (ms) on the computed retry backoff" {
    long_help #"""
Lower bound (ms) on the computed retry backoff.

Overrides `fetchRetryMintimeout` / `fetch-retry-mintimeout` from `.npmrc` / `aube-workspace.yaml` when set.
"""#
    arg <MS>
}
flag --fetch-timeout help="Per-request HTTP timeout in milliseconds" {
    long_help #"""
Per-request HTTP timeout in milliseconds.

Overrides `fetchTimeout` / `fetch-timeout` from `.npmrc` / `aube-workspace.yaml` when set. Applied via `reqwest`\'s `.timeout()` so it covers headers + body together.
"""#
    arg <MS>
}
flag --registry help="Override the default registry URL for this invocation" {
    long_help #"""
Override the default registry URL for this invocation.

Use this npm registry URL for package metadata, tarballs, audit requests, dist-tags, and registry writes.
"""#
    arg <URL>
}
flag "--disable-global-virtual-store --disable-gvs" help="Force the shared global virtual store off for this invocation" {
    long_help #"""
Force the shared global virtual store off for this invocation.

Packages are materialized inside the project\'s virtual store instead of symlinked from `~/.cache/aube/virtual-store/`.
"""#
}
flag "--enable-global-virtual-store --enable-gvs" help="Force the shared global virtual store on for this invocation" {
    long_help #"""
Force the shared global virtual store on for this invocation.

Overrides CI\'s default per-project materialization and the `disableGlobalVirtualStoreForPackages` auto-disable heuristic.
"""#
}
arg "[SCRIPT]" help="Script or local binary name" help_long=#"""
Script or local binary name.

Omit on an interactive TTY to pick from `package.json` scripts. If no script matches, aube falls back to `node_modules/.bin/<name>`.
"""# required=#false
arg "[ARGS]…" help="Arguments to pass to the script" required=#false double_dash=automatic var=#true
complete script run="aubr --complete" descriptions=#true
complete package run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete packages run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete pkg run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete bin run="aube completion _ --complete bin" descriptions=#true
complete workspace run="aube completion _ --complete workspace" descriptions=#true
complete key run="aube completion _ --complete setting" descriptions=#true
complete patch run="aube completion _ --complete patch" descriptions=#true
complete dir type=dir
complete path type=path
'
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"
set -l spec_file "$spec_dir/usage__usage_spec_aubr.spec"
echo $_usage_spec_aubr > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc aubr -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc aubr -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
# @generated by usage-cli from stdin

# if "usage" is not installed show an error
if ! type -P usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in aubx." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_aubx 'name aubx
bin aubx
version "1.38.1"
about "Fetch a package into a throwaway environment and run its binary"
flag "-C --dir --cd --prefix" help="Change to directory before running (like `make -C` or `mise --cd`)" global=#true {
    arg <DIR>
}
flag "-F --filter" help="Scope command execution to workspace packages matching PATTERN" var=#true global=#true {
    long_help #"""
Scope command execution to workspace packages matching PATTERN.

Supports exact names (`my-pkg`), globs (`@scope/*`, `*-plugin`), paths (`./packages/api`), graph selectors (`pkg...`, `...pkg`), git-ref selectors (`[origin/main]`), and exclusions (`!pkg`). Repeatable; matches are OR-ed.

Currently honored by `run`, `test`, `start`, `stop`, `restart`, `install`, `exec`, `list`, `publish`, `deploy`, `add`, `remove`, `update`, `why`, and implicit-script invocations.
"""#
    arg <WORKSPACE>
}
flag "-r --recursive" help="Run the command across every workspace package" global=#true {
    long_help #"""
Run the command across every workspace package.

Equivalent to `--filter=*`; if `--filter` is also given, `--recursive` is a no-op and the explicit filter wins. Honored by the same commands as `--filter`.
"""#
}
flag "-v --verbose" help="Enable verbose/debug logging (shortcut for `--loglevel debug`)" global=#true
flag "-V --version" help="Print version and check for updates" global=#true {
    long_help #"""
Print version and check for updates.

Manual flag so we can run the async update notifier alongside the version print — clap\'s auto `Action::Version` exits inside `parse_from`, before the tokio runtime is built.
"""#
}
flag --aggregate-output help="Group workspace command output after each package finishes" hide=#true global=#true {
    long_help #"""
Group workspace command output after each package finishes.

Accepted for pnpm compatibility; aube\'s workspace fanout is currently sequential, so output is already grouped.
"""#
}
flag --color help="Force colored output even when stderr is not a TTY" global=#true {
    long_help #"""
Force colored output even when stderr is not a TTY.

Overrides `NO_COLOR` / `CLICOLOR=0`. Mutually exclusive with `--no-color`.
"""#
}
flag --diag help="Enable cold-install deep diagnostics. Modes: summary  — sum_ms / mean / max / %wall table at end trace    — summary + critical path + starvation + what-if + lifecycle live     — like trace, plus print every span >= 100ms to stderr live full     — like trace, plus write JSONL trace to a file (defaults to ./aube-diag.jsonl)" global=#true {
    long_help #"""
Enable cold-install deep diagnostics. Modes: summary  — sum_ms / mean / max / %wall table at end trace    — summary + critical path + starvation + what-if + lifecycle live     — like trace, plus print every span >= 100ms to stderr live full     — like trace, plus write JSONL trace to a file (defaults to ./aube-diag.jsonl)

Quick form: `--diag` with no value defaults to `trace`. Output file path can be set via `--diag-file`. Threshold for live mode via `--diag-threshold-ms`.
"""#
    arg <MODE>
}
flag --diag-file help="Path for `--diag full` JSONL trace (default: ./aube-diag.jsonl)" global=#true {
    arg <PATH>
}
flag --diag-threshold-ms help="Live-mode threshold: only print spans whose duration is >= N ms (default 100)" global=#true {
    arg <MS>
}
flag --fail-if-no-match help="Error when a workspace selector matches no packages" global=#true {
    long_help #"""
Error when a workspace selector matches no packages.

Accepted globally; selected commands already fail on empty matches.
"""#
}
flag --filter-prod help="Production-only variant of `--filter`" var=#true global=#true {
    long_help #"""
Production-only variant of `--filter`.

Same selector grammar as `--filter`, but graph walks (`pkg...`, `...pkg`) only follow `dependencies` / `optionalDependencies` / `peerDependencies` edges — `devDependencies` (and packages reachable solely through them) are skipped. Non-graph forms (exact name, glob, path, `[git-ref]`) behave identically to `--filter`. Repeatable; can be combined with `--filter`.
"""#
    arg <PATTERN>
}
flag --ignore-workspace help="Ignore workspace discovery for commands that support workspace fanout" hide=#true global=#true {
    long_help #"""
Ignore workspace discovery for commands that support workspace fanout.

Parsed for pnpm compatibility.
"""#
}
flag --include-workspace-root help="Include the workspace root in recursive workspace operations" hide=#true global=#true {
    long_help #"""
Include the workspace root in recursive workspace operations.

Parsed for pnpm compatibility.
"""#
}
flag --loglevel help="Set the log level. Logs at or above this level are shown" global=#true {
    arg <LEVEL> {
        choices trace debug info warn error silent
    }
}
flag --no-color help="Disable colored output" global=#true {
    long_help #"""
Disable colored output.

Overrides `FORCE_COLOR` / `CLICOLOR_FORCE` and sets `NO_COLOR=1` so downstream libraries (miette, clx, child processes) all see the same choice.
"""#
}
flag --reporter help="Output format: default, append-only, ndjson, silent" global=#true {
    long_help #"""
Output format: default, append-only, ndjson, silent.

`default` renders the progress UI when stderr is a TTY; `append-only` disables the progress UI in favor of plain line-at-a-time logs; `ndjson` swaps the tracing fmt layer for the JSON formatter (one JSON object per log event on stderr) and is what tooling wrappers should consume; `silent` suppresses all non-error output (alias for `--loglevel silent`).
"""#
    arg <NAME> {
        choices default append-only ndjson silent
    }
}
flag --silent help="Suppress all non-error output (alias for `--loglevel silent`)" global=#true
flag --stream help="Stream workspace command output as each child process writes it" hide=#true global=#true {
    long_help #"""
Stream workspace command output as each child process writes it.

Accepted for pnpm compatibility; aube\'s workspace fanout is currently sequential.
"""#
}
flag --use-stderr help="Route lifecycle and workspace command output through stderr" hide=#true global=#true {
    long_help #"""
Route lifecycle and workspace command output through stderr.

Accepted for pnpm compatibility.
"""#
}
flag --workspace-packages help="Prefer workspace packages when resolving dependencies" hide=#true global=#true {
    long_help #"""
Prefer workspace packages when resolving dependencies.

Parsed for pnpm compatibility; aube already resolves workspace packages when a workspace is present.
"""#
}
flag --workspace-root help="Run from the workspace root regardless of the current package" global=#true
flag "-y --yes" help="Automatically answer yes to prompts" hide=#true global=#true {
    long_help #"""
Automatically answer yes to prompts.

Parsed for pnpm compatibility; aube does not currently prompt on these paths.
"""#
}
flag "-c --shell-mode" help="Run the assembled command line through `sh -c`" {
    long_help #"""
Run the assembled command line through `sh -c`.

`<scratch>/node_modules/.bin` is prepended to `PATH`. Use this for pipelines, redirects, or env expansion (`aube dlx -p cowsay -c \'cowsay hello | tr a-z A-Z\'`). Mirrors `pnpm dlx --shell-mode`.
"""#
}
flag "-p --package" help="Install a specific package (repeatable)" var=#true {
    long_help #"""
Install a specific package (repeatable).

Overrides inferring from the command.
"""#
    arg <PACKAGE>
}
flag --allow-build help="Allow named packages to run lifecycle scripts during the transient install. Use `--allow-build=<pkg>`" var=#true {
    long_help #"""
Allow named packages to run lifecycle scripts during the transient install. Use `--allow-build=<pkg>`.

Repeatable — pass once per package. The named package\'s `preinstall` / `install` / `postinstall` scripts execute during the transient install. Requires the equals form (`--allow-build=<pkg>`); space-separated forms are rejected. Mirrors pnpm\'s `pnpm dlx --allow-build=<pkg>` compatibility surface while keeping dlx scripts skipped unless explicitly approved.
"""#
    arg <PKG>
}
flag --frozen-lockfile help="Error if the lockfile drifts from package.json"
flag --no-frozen-lockfile help="Always re-resolve, even if the lockfile is up to date"
flag --prefer-frozen-lockfile help="Use the lockfile when fresh, re-resolve when stale"
flag --fetch-retries help="Number of retry attempts for failed registry fetches" {
    long_help #"""
Number of retry attempts for failed registry fetches.

Overrides `fetchRetries` / `fetch-retries` from `.npmrc` / `aube-workspace.yaml` when set. Pair with `--fetch-timeout` to fail fast in scripted test runs.
"""#
    arg <N>
}
flag --fetch-retry-factor help="Exponential backoff factor between retry attempts" {
    long_help #"""
Exponential backoff factor between retry attempts.

Overrides `fetchRetryFactor` / `fetch-retry-factor` from `.npmrc` / `aube-workspace.yaml` when set. Integer-only — the underlying `FetchPolicy.retry_factor` is `u32`. Fractional values like `1.5` are rejected by clap.
"""#
    arg <N>
}
flag --fetch-retry-maxtimeout help="Upper bound (ms) on the computed retry backoff" {
    long_help #"""
Upper bound (ms) on the computed retry backoff.

Overrides `fetchRetryMaxtimeout` / `fetch-retry-maxtimeout` from `.npmrc` / `aube-workspace.yaml` when set.
"""#
    arg <MS>
}
flag --fetch-retry-mintimeout help="Lower bound (ms) on the computed retry backoff" {
    long_help #"""
Lower bound (ms) on the computed retry backoff.

Overrides `fetchRetryMintimeout` / `fetch-retry-mintimeout` from `.npmrc` / `aube-workspace.yaml` when set.
"""#
    arg <MS>
}
flag --fetch-timeout help="Per-request HTTP timeout in milliseconds" {
    long_help #"""
Per-request HTTP timeout in milliseconds.

Overrides `fetchTimeout` / `fetch-timeout` from `.npmrc` / `aube-workspace.yaml` when set. Applied via `reqwest`\'s `.timeout()` so it covers headers + body together.
"""#
    arg <MS>
}
flag --registry help="Override the default registry URL for this invocation" {
    long_help #"""
Override the default registry URL for this invocation.

Use this npm registry URL for package metadata, tarballs, audit requests, dist-tags, and registry writes.
"""#
    arg <URL>
}
flag "--disable-global-virtual-store --disable-gvs" help="Force the shared global virtual store off for this invocation" {
    long_help #"""
Force the shared global virtual store off for this invocation.

Packages are materialized inside the project\'s virtual store instead of symlinked from `~/.cache/aube/virtual-store/`.
"""#
}
flag "--enable-global-virtual-store --enable-gvs" help="Force the shared global virtual store on for this invocation" {
    long_help #"""
Force the shared global virtual store on for this invocation.

Overrides CI\'s default per-project materialization and the `disableGlobalVirtualStoreForPackages` auto-disable heuristic.
"""#
}
arg "[PARAMS]" help="Command (binary) to run, followed by arguments to pass through to it" help_long=#"""
Command (binary) to run, followed by arguments to pass through to it.

The first positional is the command; the rest are forwarded verbatim to the binary. Without `--package`, a local `node_modules/.bin/<command>` wins when present; otherwise dlx installs into a throwaway project. Under `--shell-mode`/`-c` the positionals are joined and evaluated by `sh -c` instead of looked up directly.
"""# required=#false double_dash=automatic var_max=1
complete package run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete packages run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete pkg run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
complete bin run="aube completion _ --complete bin" descriptions=#true
complete workspace run="aube completion _ --complete workspace" descriptions=#true
complete key run="aube completion _ --complete setting" descriptions=#true
complete patch run="aube completion _ --complete patch" descriptions=#true
complete dir type=dir
complete path type=path
complete params run="aube completion _ --complete package --query=\'{{ words[CURRENT] | replace(from=\"\'\", to=\"\'\\\\\'\'\") }}\'" descriptions=#true
'
set -l spec_dir (if set -q XDG_CACHE_HOME; echo $XDG_CACHE_HOME; else; echo $HOME/.cache; end)/usage
test -d "$spec_dir"; or mkdir -p -m 700 "$spec_dir"
set -l spec_file "$spec_dir/usage__usage_spec_aubx.spec"
echo $_usage_spec_aubx > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc aubx -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc aubx -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
