# lazyworktree fish shell completion

function __fish_lazyworktree_no_subcommand --description 'Test if there has been any subcommand yet'
    for i in (commandline -opc)
        if contains -- $i create rename delete list ls exec help h completion
            return 1
        end
    end
    return 0
end

complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l worktree-dir -s w -r -d 'Override the default worktree root directory'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l debug-log -r -d 'Path to debug log file'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l output-selection -r -d 'Write selected worktree path to a file'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l theme -s t -r -d 'Override the UI theme (dracula, dracula-light, narna, clean-light, catppuccin-latte, rose-pine-dawn, one-light, everforest-light, everforest-dark, solarized-dark, solarized-light, gruvbox-dark, gruvbox-light, nord, monokai, catppuccin-mocha, modern, tokyo-night, one-dark, rose-pine, ayu-mirage, kanagawa)'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l search-auto-select -d 'Start with filter focused'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l show-syntax-themes -d 'List available delta syntax themes'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l config-file -r -d 'Path to configuration file'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l config -s C -r -d 'Override config values (repeatable): --config=lw.key=value'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l help -s h -d 'show help'
complete -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -f -l version -s v -d 'print the version'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'create' -d 'Create a new worktree'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l from-branch -r -d 'Create worktree from branch (defaults to current branch)'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l from-pr -r -d 'Create worktree from PR number'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l from-issue -r -d 'Create worktree from issue number'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l from-issue-interactive -s I -d 'Interactively select an issue to create worktree from'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l from-pr-interactive -s P -d 'Interactively select a PR to create worktree from'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l generate -d 'Generate name automatically from the current branch'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l with-change -d 'Carry over uncommitted changes to the new worktree'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l no-workspace -s N -d 'Create local branch and switch to it without creating a worktree (requires --from-pr, --from-pr-interactive, --from-issue, or --from-issue-interactive)'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l silent -d 'Suppress progress messages'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l output-selection -r -d 'Write created worktree path to a file'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l exec -s x -r -d 'Run a shell command after creation (in the created worktree, or current directory with --no-workspace)'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l query -s q -r -d 'Pre-filter interactive selection (pre-fills fzf search or filters numbered list); requires --from-pr-interactive or --from-issue-interactive'
complete -c lazyworktree -n '__fish_seen_subcommand_from create' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'rename' -d 'Rename a worktree'
complete -c lazyworktree -n '__fish_seen_subcommand_from rename' -f -l silent -d 'Suppress progress messages'
complete -c lazyworktree -n '__fish_seen_subcommand_from rename' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from rename; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'delete' -d 'Delete a worktree'
complete -c lazyworktree -n '__fish_seen_subcommand_from delete' -f -l no-branch -d 'Skip branch deletion'
complete -c lazyworktree -n '__fish_seen_subcommand_from delete' -f -l silent -d 'Suppress progress messages'
complete -c lazyworktree -n '__fish_seen_subcommand_from delete' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'list' -d 'List all worktrees'
complete -c lazyworktree -n '__fish_seen_subcommand_from list ls' -f -l pristine -s p -d 'Output paths only (one per line, suitable for scripting)'
complete -c lazyworktree -n '__fish_seen_subcommand_from list ls' -f -l json -d 'Output as JSON'
complete -c lazyworktree -n '__fish_seen_subcommand_from list ls' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from list ls; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'exec' -d 'Run a command or trigger a key action in a worktree'
complete -c lazyworktree -n '__fish_seen_subcommand_from exec' -f -l workspace -s w -r -d 'Target worktree name or path'
complete -c lazyworktree -n '__fish_seen_subcommand_from exec' -f -l key -s k -r -d 'Custom command key to trigger (e.g. \'t\' for tmux)'
complete -c lazyworktree -n '__fish_seen_subcommand_from exec' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from exec; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
complete -x -c lazyworktree -n '__fish_lazyworktree_no_subcommand' -a 'help' -d 'Shows a list of commands or help for one command'
complete -c lazyworktree -n '__fish_seen_subcommand_from completion' -f -l help -s h -d 'show help'
complete -x -c lazyworktree -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from help h' -a 'help' -d 'Shows a list of commands or help for one command'
