# Command completion for pkl
# Generated by Clikt


### Setup for pkl
set -l pkl_subcommands 'eval repl server test project download-package analyze format run shell-completion'

## Options for pkl
complete -c pkl -n "not __fish_seen_subcommand_from $pkl_subcommands" -s v -l version -d 'Show the version and exit'
complete -c pkl -n "not __fish_seen_subcommand_from $pkl_subcommands" -s h -l help -d 'Show this message and exit'


### Setup for eval
complete -c pkl -f -n __fish_use_subcommand -a eval -d 'Render pkl module(s)'

## Options for eval
complete -c pkl -n "__fish_seen_subcommand_from eval" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s o -l output-path -r -F -d 'File path where the output file is placed.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l module-output-separator -r -d 'Separator to use when multiple module outputs are written to the same file. (default: ---)'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s x -l expression -r -d 'Expression to be evaluated within the module.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s m -l multiple-file-output-path -r -F -d 'Directory where a module\'s multiple file output is placed.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -l power-assertions -l no-power-assertions -d 'Enable power assertions for detailed assertion failure messages.'
complete -c pkl -n "__fish_seen_subcommand_from eval" -s h -l help -d 'Show this message and exit'

## Arguments for eval
complete -c pkl -n "__fish_seen_subcommand_from eval" -F -d 'Module paths or URIs to evaluate.'


### Setup for repl
complete -c pkl -f -n __fish_use_subcommand -a repl -d 'Start a REPL session'

## Options for repl
complete -c pkl -n "__fish_seen_subcommand_from repl" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from repl" -s h -l help -d 'Show this message and exit'


### Setup for server
complete -c pkl -f -n __fish_use_subcommand -a server -d 'Run as a server that communicates over standard input/output'

## Options for server
complete -c pkl -n "__fish_seen_subcommand_from server" -s h -l help -d 'Show this message and exit'


### Setup for test
complete -c pkl -f -n __fish_use_subcommand -a test -d 'Run tests within the given module(s)'

## Options for test
complete -c pkl -n "__fish_seen_subcommand_from test" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from test" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from test" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from test" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from test" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from test" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from test" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from test" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from test" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from test" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from test" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l junit-reports -r -F -d 'Directory where to store JUnit reports.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l junit-aggregate-reports -d 'Aggregate JUnit reports into a single file.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l junit-aggregate-suite-name -r -d 'The name of the root JUnit test suite.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l overwrite -d 'Force generation of expected examples.'
complete -c pkl -n "__fish_seen_subcommand_from test" -l power-assertions -l no-power-assertions -d 'Enable power assertions for detailed assertion failure messages.'
complete -c pkl -n "__fish_seen_subcommand_from test" -s h -l help -d 'Show this message and exit'

## Arguments for test
complete -c pkl -n "__fish_seen_subcommand_from test" -F -d 'Module paths or URIs to evaluate.'


### Setup for project
set -l pkl_project_subcommands 'resolve package'
complete -c pkl -f -n __fish_use_subcommand -a project -d 'Run commands related to projects'

## Options for project
complete -c pkl -n "__fish_seen_subcommand_from project" -s h -l help -d 'Show this message and exit'


### Setup for resolve
complete -c pkl -f -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from $pkl_project_subcommands" -a resolve -d '
  Resolve dependencies for project(s)

  This command takes the `dependencies` of `PklProject`s, and writes the
  resolved versions to `PklProject.deps.json` files.

  Examples:

  ```
  # Search the current working directory for a project, and resolve its dependencies.
  $ pkl project resolve

  # Resolve dependencies for all projects within the `packages/` directory.
  $ pkl project resolve packages/*/
  ```
  '

## Options for resolve
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from resolve" -s h -l help -d 'Show this message and exit'

## Arguments for resolve
complete -c pkl -n "__fish_seen_subcommand_from resolve" -F -d 'The project directories to resolve dependencies for'


### Setup for package
complete -c pkl -f -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from $pkl_project_subcommands" -a package -d 'Verify package(s), and prepare package artifacts to be published.

This command runs a project\'s api tests, as defined by `apiTests` in `PklProject`.
Additionally, it verifies that all imports resolve to paths that are local to the project.

Finally, this command writes the following artifacts into the output directory specified by the output path.

  - `name@version` - dependency metadata

  - `name@version.sha256` - dependency metadata\'s SHA-256 checksum

  - `name@version.zip` - package archive

  - `name@version.zip.sha256` - package archive\'s SHA-256 checksum

The output path option accepts the following placeholders:

  - %{name}: The display name of the package

  - %{version}: The version of the package

If a project has local project dependencies, the depended upon project directories must also
be included as arguments to this command.

Examples:

```
# Search the current working directory for a project, and package it.
$ pkl project package

# Package all projects within the `packages/` directory.
$ pkl project package packages/*/
```'

## Options for package
complete -c pkl -n "__fish_seen_subcommand_from package" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from package" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from package" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from package" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from package" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from package" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from package" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from package" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from package" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from package" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from package" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l junit-reports -r -F -d 'Directory where to store JUnit reports.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l junit-aggregate-reports -d 'Aggregate JUnit reports into a single file.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l junit-aggregate-suite-name -r -d 'The name of the root JUnit test suite.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l overwrite -d 'Force generation of expected examples.'
complete -c pkl -n "__fish_seen_subcommand_from package" -l output-path -r -F -d 'The directory to write artifacts to'
complete -c pkl -n "__fish_seen_subcommand_from package" -l skip-publish-check -d 'Skip checking if a package has already been published with different contents'
complete -c pkl -n "__fish_seen_subcommand_from package" -s h -l help -d 'Show this message and exit'

## Arguments for package
complete -c pkl -n "__fish_seen_subcommand_from package" -F -d 'The project directories to package'


### Setup for download-package
complete -c pkl -f -n __fish_use_subcommand -a download-package -d 'Download package(s)

This command downloads the specified packages to the cache directory.
If the package already exists in the cache directory, this command is a no-op.

Examples:

```
# Download two packages
$ pkl download-package package://example.com/package1@1.0.0 package://example.com/package2@1.0.0 
```'

## Options for download-package
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -l no-transitive -d 'Skip downloading transitive dependencies of a package'
complete -c pkl -n "__fish_seen_subcommand_from download-package" -s h -l help -d 'Show this message and exit'

## Arguments for download-package
complete -c pkl -n "__fish_seen_subcommand_from download-package" -d 'The package URIs to download'


### Setup for analyze
set -l pkl_analyze_subcommands 'imports'
complete -c pkl -f -n __fish_use_subcommand -a analyze -d 'Commands related to static analysis'

## Options for analyze
complete -c pkl -n "__fish_seen_subcommand_from analyze" -s h -l help -d 'Show this message and exit'


### Setup for imports
complete -c pkl -f -n "__fish_seen_subcommand_from analyze; and not __fish_seen_subcommand_from $pkl_analyze_subcommands" -a imports -d 'Prints the graph of modules imported by the input module(s).'

## Options for imports
complete -c pkl -n "__fish_seen_subcommand_from imports" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s o -l output-path -r -F -d 'File path where the output file is placed.'
complete -c pkl -n "__fish_seen_subcommand_from imports" -s h -l help -d 'Show this message and exit'

## Arguments for imports
complete -c pkl -n "__fish_seen_subcommand_from imports" -F -d 'Module paths or URIs to evaluate.'


### Setup for format
complete -c pkl -f -n __fish_use_subcommand -a format -d 'Format or check formatting of Pkl files.

Examples:

```
# Overwrite all Pkl files inside `my/folder/`, recursively.
$ pkl format -w my/folder/

# Check formatting of all files, printing filenames with formatting violations to stdout.
# Exit with exit code `11` if formatting violations were found.
$ pkl format --diff-name-only my/folder/

# Format Pkl code from stdin.
$ echo "foo = 1" | pkl format -
```'

## Options for format
complete -c pkl -n "__fish_seen_subcommand_from format" -l grammar-version -r -fa "1 2" -d 'The grammar compatibility version to use.
'
complete -c pkl -n "__fish_seen_subcommand_from format" -s w -l write -d 'Format files in place, overwriting them. Implies `---diff-name-only`.'
complete -c pkl -n "__fish_seen_subcommand_from format" -l diff-name-only -d 'Write the path of files with formatting violations to stdout.'
complete -c pkl -n "__fish_seen_subcommand_from format" -s s -l silent -d 'Don\'t write to stdout or stderr. Mutually exclusive with `--diff-name-only`.'
complete -c pkl -n "__fish_seen_subcommand_from format" -s h -l help -d 'Show this message and exit'

## Arguments for format
complete -c pkl -n "__fish_seen_subcommand_from format" -F -d 'Files or directory to check. Use `-` to read from stdin.'


### Setup for run
complete -c pkl -f -n __fish_use_subcommand -a run -d 'Run a Pkl pkl:Command CLI tool'

## Options for run
complete -c pkl -n "__fish_seen_subcommand_from run" -l allowed-modules -r -d 'URI patterns that determine which modules can be loaded and evaluated.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l allowed-resources -r -d 'URI patterns that determine which external resources can be read.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l root-dir -r -F -d 'Restricts access to file-based modules and resources to those located under the root directory.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l cache-dir -r -F -d 'The cache directory for storing packages.'
complete -c pkl -n "__fish_seen_subcommand_from run" -s w -l working-dir -r -F -d 'Base path that relative module paths are resolved against.'
complete -c pkl -n "__fish_seen_subcommand_from run" -s p -l property -r -d 'External property to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from run" -l color -r -fa "never auto always" -d 'Whether to format messages in ANSI color. Possible values of <when> are \'never\', \'auto\', and \'always\'.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l no-cache -d 'Disable caching of packages'
complete -c pkl -n "__fish_seen_subcommand_from run" -s f -l format -r -fa "json jsonnet pcf properties plist textproto xml yaml pkl-binary" -d 'Output format to generate. <json, jsonnet, pcf, properties, plist, textproto, xml, yaml, pkl-binary>'
complete -c pkl -n "__fish_seen_subcommand_from run" -s e -l env-var -r -d 'Environment variable to set (repeatable).'
complete -c pkl -n "__fish_seen_subcommand_from run" -l module-path -r -F -d 'Directories, ZIP archives, or JAR archives to search when resolving `modulepath:` URIs.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l settings -r -F -d 'Pkl settings module to use.'
complete -c pkl -n "__fish_seen_subcommand_from run" -s t -l timeout -r -d 'Duration, in seconds, after which evaluation of a source module will be timed out.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l ca-certificates -r -F -d 'Only trust CA certificates from the provided file(s).'
complete -c pkl -n "__fish_seen_subcommand_from run" -l http-proxy -r -d 'Proxy to use for HTTP(S) connections.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l http-no-proxy -r -d 'Hostnames that should not be connected to via a proxy.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l http-rewrite -r -d 'URL prefixes that should be rewritten.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l external-module-reader -r -d 'External reader registrations for module URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from run" -l external-resource-reader -r -d 'External reader registrations for resource URI schemes'
complete -c pkl -n "__fish_seen_subcommand_from run" -l trace-mode -r -fa "compact pretty" -d 'Specifies how calls to trace() are formatted. Possible values of <style> are \'compact\' and \'pretty\'.'
complete -c pkl -n "__fish_seen_subcommand_from run" -s h -l help -d 'Show this message and exit'
complete -c pkl -n "__fish_seen_subcommand_from run" -l project-dir -r -F -d 'The project directory to use for this command. By default, searches up from the working directory for a PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l omit-project-settings -d 'Ignores evaluator settings set in the PklProject file.'
complete -c pkl -n "__fish_seen_subcommand_from run" -l no-project -d 'Disables loading settings and dependencies from the PklProject file.'

## Arguments for run
complete -c pkl -n "__fish_seen_subcommand_from run" -F -d 'Root pkl:Command module to invoke.'
complete -c pkl -n "__fish_seen_subcommand_from run"


### Setup for shell-completion
complete -c pkl -f -n __fish_use_subcommand -a shell-completion -d 'Generate a completion script for the given shell'

## Options for shell-completion
complete -c pkl -n "__fish_seen_subcommand_from shell-completion" -s h -l help -d 'Show this message and exit'

## Arguments for shell-completion
complete -c pkl -n "__fish_seen_subcommand_from shell-completion" -fa "bash zsh fish"

