complete -c procs -s W -l watch-interval -d 'Watch mode with custom interval' -r
complete -c procs -s c -l color -d 'Color mode' -r -f -a "auto\t''
always\t''
disable\t''"
complete -c procs -l theme -d 'Theme mode' -r -f -a "auto\t''
dark\t''
light\t''"
complete -c procs -s p -l pager -d 'Pager mode' -r -f -a "auto\t''
always\t''
disable\t''"
complete -c procs -l interval -d 'Interval to calculate throughput' -r
complete -c procs -l use-config -d 'Use built-in configuration' -r -f -a "default\t''
large\t''"
complete -c procs -l load-config -d 'Load configuration from file' -r -F
complete -c procs -l gen-completion -d 'Generate shell completion file' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c procs -l gen-completion-out -d 'Generate shell completion file and write to stdout' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c procs -l procfs -d 'Path to procfs' -r -F
complete -c procs -l sorta -d 'Sort column by ascending' -r -f -a "ccgroup\t'Control group by compressed format'
cgroup\t'Control group'
command\t'Command with all arguments'
contextsw\t'Context switch count'
voluntarycontextsw\t'Voluntary context switch count'
involuntarycontextsw\t'Involuntary context switch count'
cputime\t'Cumulative CPU time'
docker\t'Docker container name'
eip\t'Instruction pointer'
elapsedtime\t'Elapsed time'
empty\t'Empty'
env\t'Environment variables'
esp\t'Stack pointer'
filename\t'File name'
gid\t'Group ID'
gidfs\t'File system group ID'
gidreal\t'Real group ID'
gidsaved\t'Saved group ID'
group\t'Group name'
groupfs\t'File system group name'
groupreal\t'Real group name'
groupsaved\t'Saved group name'
majflt\t'Major page fault count'
minflt\t'Minor page fault count'
multislot\t'Slot for `--insert` option'
nice\t'Nice value'
pgid\t'Process group ID'
pid\t'Process ID'
policy\t'Scheduling policy'
ppid\t'Parent process ID'
priority\t'Priority'
processor\t'Currently assigned processor'
readbytes\t'Read bytes from storage'
rtpriority\t'Real-time priority'
seccontext\t'Security context'
separator\t'Show | for column separation'
session\t'Process Session ID'
shdpnd\t'Pending signal mask for process'
slot\t'Slot for `--insert` option'
sigblk\t'Blocked signal mask'
sigcgt\t'Caught signal mask'
sigign\t'Ignored signal mask'
sigpnd\t'Pending signal mask for thread'
ssb\t'Speculative store bypass status'
starttime\t'Starting time'
state\t'Process state'
tcpport\t'Bound TCP ports'
threads\t'Thread count'
treeslot\t'Slot for tree column'
tty\t'Controlling TTY'
udpport\t'Bound UDP ports'
uid\t'User ID'
uidfs\t'File system user ID'
uidlogin\t'Login user ID'
uidreal\t'Real user ID'
uidsaved\t'Saved user ID'
usagecpu\t'CPU utilization'
usagemem\t'Memory utilization'
user\t'User name'
userfs\t'File system user name'
userlogin\t'Login user name'
userreal\t'Real user name'
usersaved\t'Saved user name'
vmdata\t'Data size'
vmexe\t'Text segments size'
vmhwm\t'Peak resident set size'
vmlib\t'Library code size'
vmlock\t'Locked memory size'
vmpeak\t'Peak virtual memory size'
vmpin\t'Pinned memory size'
vmpte\t'Page table entries size'
vmrss\t'Resident set size'
vmsize\t'Physical page size'
vmstack\t'Stack size'
vmswap\t'Swapped-out virtual memory size'
wchan\t'Process sleeping kernel function'
workdir\t'Current working directory'
writebytes\t'Write bytes to storage'"
complete -c procs -l sortd -d 'Sort column by descending' -r -f -a "ccgroup\t'Control group by compressed format'
cgroup\t'Control group'
command\t'Command with all arguments'
contextsw\t'Context switch count'
voluntarycontextsw\t'Voluntary context switch count'
involuntarycontextsw\t'Involuntary context switch count'
cputime\t'Cumulative CPU time'
docker\t'Docker container name'
eip\t'Instruction pointer'
elapsedtime\t'Elapsed time'
empty\t'Empty'
env\t'Environment variables'
esp\t'Stack pointer'
filename\t'File name'
gid\t'Group ID'
gidfs\t'File system group ID'
gidreal\t'Real group ID'
gidsaved\t'Saved group ID'
group\t'Group name'
groupfs\t'File system group name'
groupreal\t'Real group name'
groupsaved\t'Saved group name'
majflt\t'Major page fault count'
minflt\t'Minor page fault count'
multislot\t'Slot for `--insert` option'
nice\t'Nice value'
pgid\t'Process group ID'
pid\t'Process ID'
policy\t'Scheduling policy'
ppid\t'Parent process ID'
priority\t'Priority'
processor\t'Currently assigned processor'
readbytes\t'Read bytes from storage'
rtpriority\t'Real-time priority'
seccontext\t'Security context'
separator\t'Show | for column separation'
session\t'Process Session ID'
shdpnd\t'Pending signal mask for process'
slot\t'Slot for `--insert` option'
sigblk\t'Blocked signal mask'
sigcgt\t'Caught signal mask'
sigign\t'Ignored signal mask'
sigpnd\t'Pending signal mask for thread'
ssb\t'Speculative store bypass status'
starttime\t'Starting time'
state\t'Process state'
tcpport\t'Bound TCP ports'
threads\t'Thread count'
treeslot\t'Slot for tree column'
tty\t'Controlling TTY'
udpport\t'Bound UDP ports'
uid\t'User ID'
uidfs\t'File system user ID'
uidlogin\t'Login user ID'
uidreal\t'Real user ID'
uidsaved\t'Saved user ID'
usagecpu\t'CPU utilization'
usagemem\t'Memory utilization'
user\t'User name'
userfs\t'File system user name'
userlogin\t'Login user name'
userreal\t'Real user name'
usersaved\t'Saved user name'
vmdata\t'Data size'
vmexe\t'Text segments size'
vmhwm\t'Peak resident set size'
vmlib\t'Library code size'
vmlock\t'Locked memory size'
vmpeak\t'Peak virtual memory size'
vmpin\t'Pinned memory size'
vmpte\t'Page table entries size'
vmrss\t'Resident set size'
vmsize\t'Physical page size'
vmstack\t'Stack size'
vmswap\t'Swapped-out virtual memory size'
wchan\t'Process sleeping kernel function'
workdir\t'Current working directory'
writebytes\t'Write bytes to storage'"
complete -c procs -s i -l insert -d 'Insert column to slot' -r -f -a "ccgroup\t'Control group by compressed format'
cgroup\t'Control group'
command\t'Command with all arguments'
contextsw\t'Context switch count'
voluntarycontextsw\t'Voluntary context switch count'
involuntarycontextsw\t'Involuntary context switch count'
cputime\t'Cumulative CPU time'
docker\t'Docker container name'
eip\t'Instruction pointer'
elapsedtime\t'Elapsed time'
empty\t'Empty'
env\t'Environment variables'
esp\t'Stack pointer'
filename\t'File name'
gid\t'Group ID'
gidfs\t'File system group ID'
gidreal\t'Real group ID'
gidsaved\t'Saved group ID'
group\t'Group name'
groupfs\t'File system group name'
groupreal\t'Real group name'
groupsaved\t'Saved group name'
majflt\t'Major page fault count'
minflt\t'Minor page fault count'
multislot\t'Slot for `--insert` option'
nice\t'Nice value'
pgid\t'Process group ID'
pid\t'Process ID'
policy\t'Scheduling policy'
ppid\t'Parent process ID'
priority\t'Priority'
processor\t'Currently assigned processor'
readbytes\t'Read bytes from storage'
rtpriority\t'Real-time priority'
seccontext\t'Security context'
separator\t'Show | for column separation'
session\t'Process Session ID'
shdpnd\t'Pending signal mask for process'
slot\t'Slot for `--insert` option'
sigblk\t'Blocked signal mask'
sigcgt\t'Caught signal mask'
sigign\t'Ignored signal mask'
sigpnd\t'Pending signal mask for thread'
ssb\t'Speculative store bypass status'
starttime\t'Starting time'
state\t'Process state'
tcpport\t'Bound TCP ports'
threads\t'Thread count'
treeslot\t'Slot for tree column'
tty\t'Controlling TTY'
udpport\t'Bound UDP ports'
uid\t'User ID'
uidfs\t'File system user ID'
uidlogin\t'Login user ID'
uidreal\t'Real user ID'
uidsaved\t'Saved user ID'
usagecpu\t'CPU utilization'
usagemem\t'Memory utilization'
user\t'User name'
userfs\t'File system user name'
userlogin\t'Login user name'
userreal\t'Real user name'
usersaved\t'Saved user name'
vmdata\t'Data size'
vmexe\t'Text segments size'
vmhwm\t'Peak resident set size'
vmlib\t'Library code size'
vmlock\t'Locked memory size'
vmpeak\t'Peak virtual memory size'
vmpin\t'Pinned memory size'
vmpte\t'Page table entries size'
vmrss\t'Resident set size'
vmsize\t'Physical page size'
vmstack\t'Stack size'
vmswap\t'Swapped-out virtual memory size'
wchan\t'Process sleeping kernel function'
workdir\t'Current working directory'
writebytes\t'Write bytes to storage'"
complete -c procs -l only -d 'Specified column only' -r -f -a "ccgroup\t'Control group by compressed format'
cgroup\t'Control group'
command\t'Command with all arguments'
contextsw\t'Context switch count'
voluntarycontextsw\t'Voluntary context switch count'
involuntarycontextsw\t'Involuntary context switch count'
cputime\t'Cumulative CPU time'
docker\t'Docker container name'
eip\t'Instruction pointer'
elapsedtime\t'Elapsed time'
empty\t'Empty'
env\t'Environment variables'
esp\t'Stack pointer'
filename\t'File name'
gid\t'Group ID'
gidfs\t'File system group ID'
gidreal\t'Real group ID'
gidsaved\t'Saved group ID'
group\t'Group name'
groupfs\t'File system group name'
groupreal\t'Real group name'
groupsaved\t'Saved group name'
majflt\t'Major page fault count'
minflt\t'Minor page fault count'
multislot\t'Slot for `--insert` option'
nice\t'Nice value'
pgid\t'Process group ID'
pid\t'Process ID'
policy\t'Scheduling policy'
ppid\t'Parent process ID'
priority\t'Priority'
processor\t'Currently assigned processor'
readbytes\t'Read bytes from storage'
rtpriority\t'Real-time priority'
seccontext\t'Security context'
separator\t'Show | for column separation'
session\t'Process Session ID'
shdpnd\t'Pending signal mask for process'
slot\t'Slot for `--insert` option'
sigblk\t'Blocked signal mask'
sigcgt\t'Caught signal mask'
sigign\t'Ignored signal mask'
sigpnd\t'Pending signal mask for thread'
ssb\t'Speculative store bypass status'
starttime\t'Starting time'
state\t'Process state'
tcpport\t'Bound TCP ports'
threads\t'Thread count'
treeslot\t'Slot for tree column'
tty\t'Controlling TTY'
udpport\t'Bound UDP ports'
uid\t'User ID'
uidfs\t'File system user ID'
uidlogin\t'Login user ID'
uidreal\t'Real user ID'
uidsaved\t'Saved user ID'
usagecpu\t'CPU utilization'
usagemem\t'Memory utilization'
user\t'User name'
userfs\t'File system user name'
userlogin\t'Login user name'
userreal\t'Real user name'
usersaved\t'Saved user name'
vmdata\t'Data size'
vmexe\t'Text segments size'
vmhwm\t'Peak resident set size'
vmlib\t'Library code size'
vmlock\t'Locked memory size'
vmpeak\t'Peak virtual memory size'
vmpin\t'Pinned memory size'
vmpte\t'Page table entries size'
vmrss\t'Resident set size'
vmsize\t'Physical page size'
vmstack\t'Stack size'
vmswap\t'Swapped-out virtual memory size'
wchan\t'Process sleeping kernel function'
workdir\t'Current working directory'
writebytes\t'Write bytes to storage'"
complete -c procs -l text -d 'Use plain text search mode (default)'
complete -c procs -l regex -d 'Use regex search mode (single PATTERN)'
complete -c procs -l smart -d 'Use smart mode (auto-detect regex syntax)'
complete -c procs -s a -l and -d 'AND  logic for multi-keyword'
complete -c procs -s o -l or -d 'OR   logic for multi-keyword'
complete -c procs -s d -l nand -d 'NAND logic for multi-keyword'
complete -c procs -s r -l nor -d 'NOR  logic for multi-keyword'
complete -c procs -s l -l list -d 'Show list of kind'
complete -c procs -l thread -d 'Show thread'
complete -c procs -s t -l tree -d 'Tree view'
complete -c procs -s w -l watch -d 'Watch mode with default interval (1s)'
complete -c procs -l json -d 'JSON output'
complete -c procs -l gen-config -d 'Generate configuration sample file'
complete -c procs -l gen-man-page -d 'Generate man page and write to stdout'
complete -c procs -l no-header -d 'Suppress header'
complete -c procs -l debug -d 'Show debug message'
complete -c procs -s h -l help -d 'Print help (see more with \'--help\')'
complete -c procs -s V -l version -d 'Print version'
