---@type table
local parsers = {
    recommended = {
        "jq",
        "jsdoc",
        "tsx",
        "typescript",
        "xml",
        "typst",
        "vhs",
        "comment",
        "fennel",
        "go",
        "gomod",
        "gosum",
        "kdl",
        "latex",
        "pymanifest",
        "python",
        "requirements",
        "ron",
        "rst",
        "ruby",
        "sql",
        "svelte",
        "tsv",
        "vue",
        "gleam",
        "graphql",
        "haskell",
        "haskell_persistent",
        "c_sharp",
        "cpp",
        "cmake",
        "commonlisp",
        "css",
    },
    linux = {
        "tmux",
        "rasi",
        "nginx",
        "nix",
        "ssh_config",
        "superhtml",
        "swift",
        "terraform",
        "xresources",
        "zig",
        "djot",
        "elixir",
        "elm",
        "elvish",
        "erlang",
        "desktop",
        "gpg",
        "just",
        "http",
    },
}

return parsers
