--load(io.popen("oh-my-posh init cmd"):read("*a"))()
--load(io.popen("oh-my-posh init cmd --config 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/refs/heads/main/themes/tokyonight_storm.omp.json'"):read("*a"))()
