-- 参考: https://karukichi-blog.netlify.app/blogs/wezterm
local wezterm = require("wezterm")
local action = wezterm.action

return {
    -- キーバインドの設定
    -- leader keyを CTRL + qにマッピング
    leader = { key = "q", mods = "CTRL", timeout_milliseconds = 1000 },
    keys = {
        { key = "Tab", mods = "CTRL", action = action.ActivateTabRelative(1) },
        { key = "Tab", mods = "SHIFT|CTRL", action = action.ActivateTabRelative(-1) },
        -- SHIFT + Enter でQuickSelect・・・画面に表示されている文字をクイックにコピペできる機能
        { key = "Enter", mods = "SHIFT", action = action.QuickSelect },
        { key = "Enter", mods = "ALT", action = action.ToggleFullScreen },
        { key = "!", mods = "CTRL", action = action.ActivateTab(0) },
        { key = "!", mods = "SHIFT|CTRL", action = action.ActivateTab(0) },
        { key = '"', mods = "ALT|CTRL", action = action.SplitVertical({ domain = "CurrentPaneDomain" }) },
        { key = '"', mods = "SHIFT|ALT|CTRL", action = action.SplitVertical({ domain = "CurrentPaneDomain" }) },
        { key = "#", mods = "CTRL", action = action.ActivateTab(2) },
        { key = "#", mods = "SHIFT|CTRL", action = action.ActivateTab(2) },
        { key = "$", mods = "CTRL", action = action.ActivateTab(3) },
        { key = "$", mods = "SHIFT|CTRL", action = action.ActivateTab(3) },
        { key = "%", mods = "CTRL", action = action.ActivateTab(4) },
        { key = "%", mods = "SHIFT|CTRL", action = action.ActivateTab(4) },
        { key = "%", mods = "ALT|CTRL", action = action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
        { key = "%", mods = "SHIFT|ALT|CTRL", action = action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
        { key = "&", mods = "CTRL", action = action.ActivateTab(6) },
        { key = "&", mods = "SHIFT|CTRL", action = action.ActivateTab(6) },
        { key = "'", mods = "SHIFT|ALT|CTRL", action = action.SplitVertical({ domain = "CurrentPaneDomain" }) },
        { key = "(", mods = "CTRL", action = action.ActivateTab(-1) },
        { key = "(", mods = "SHIFT|CTRL", action = action.ActivateTab(-1) },
        { key = ")", mods = "CTRL", action = action.ResetFontSize },
        { key = ")", mods = "SHIFT|CTRL", action = action.ResetFontSize },
        { key = "*", mods = "CTRL", action = action.ActivateTab(7) },
        { key = "*", mods = "SHIFT|CTRL", action = action.ActivateTab(7) },
        { key = "+", mods = "CTRL", action = action.IncreaseFontSize },
        { key = "+", mods = "SHIFT|CTRL", action = action.IncreaseFontSize },
        { key = "-", mods = "CTRL", action = action.DecreaseFontSize },
        { key = "-", mods = "SHIFT|CTRL", action = action.DecreaseFontSize },
        { key = "-", mods = "SUPER", action = action.DecreaseFontSize },
        -- LEADER + - でPANEを水平方向に開く
        { key = "-", mods = "LEADER", action = action.SplitVertical({ domain = "CurrentPaneDomain" }) },
        { key = "0", mods = "CTRL", action = action.ResetFontSize },
        { key = "0", mods = "SHIFT|CTRL", action = action.ResetFontSize },
        { key = "0", mods = "SUPER", action = action.ResetFontSize },
        { key = "1", mods = "SHIFT|CTRL", action = action.ActivateTab(0) },
        { key = "1", mods = "SUPER", action = action.ActivateTab(0) },
        -- LEADER + numberでタブの切り替え
        { key = "1", mods = "LEADER", action = action.ActivateTab(0) },
        { key = "2", mods = "SHIFT|CTRL", action = action.ActivateTab(1) },
        { key = "2", mods = "SUPER", action = action.ActivateTab(1) },
        -- LEADER + numberでタブの切り替え
        { key = "2", mods = "LEADER", action = action.ActivateTab(1) },
        { key = "3", mods = "SHIFT|CTRL", action = action.ActivateTab(2) },
        { key = "3", mods = "SUPER", action = action.ActivateTab(2) },
        -- LEADER + numberでタブの切り替え
        { key = "3", mods = "LEADER", action = action.ActivateTab(2) },
        { key = "4", mods = "SHIFT|CTRL", action = action.ActivateTab(3) },
        { key = "4", mods = "SUPER", action = action.ActivateTab(3) },
        -- LEADER + numberでタブの切り替え
        { key = "4", mods = "LEADER", action = action.ActivateTab(3) },
        { key = "5", mods = "SHIFT|CTRL", action = action.ActivateTab(4) },
        { key = "5", mods = "SHIFT|ALT|CTRL", action = action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
        { key = "5", mods = "SUPER", action = action.ActivateTab(4) },
        -- LEADER + numberでタブの切り替え
        { key = "5", mods = "LEADER", action = action.ActivateTab(4) },
        { key = "6", mods = "SHIFT|CTRL", action = action.ActivateTab(5) },
        { key = "6", mods = "SUPER", action = action.ActivateTab(5) },
        -- LEADER + numberでタブの切り替え
        { key = "6", mods = "LEADER", action = action.ActivateTab(5) },
        { key = "7", mods = "SHIFT|CTRL", action = action.ActivateTab(6) },
        { key = "7", mods = "SUPER", action = action.ActivateTab(6) },
        -- LEADER + numberでタブの切り替え
        { key = "7", mods = "LEADER", action = action.ActivateTab(6) },
        { key = "8", mods = "SHIFT|CTRL", action = action.ActivateTab(7) },
        { key = "8", mods = "SUPER", action = action.ActivateTab(7) },
        -- LEADER + numberでタブの切り替え
        { key = "8", mods = "LEADER", action = action.ActivateTab(7) },
        { key = "9", mods = "SHIFT|CTRL", action = action.ActivateTab(-1) },
        { key = "9", mods = "SUPER", action = action.ActivateTab(-1) },
        -- LEADER + numberでタブの切り替え
        { key = "9", mods = "LEADER", action = action.ActivateTab(8) },
        { key = "=", mods = "CTRL", action = action.IncreaseFontSize },
        { key = "=", mods = "SHIFT|CTRL", action = action.IncreaseFontSize },
        { key = "=", mods = "SUPER", action = action.IncreaseFontSize },
        { key = "@", mods = "CTRL", action = action.ActivateTab(1) },
        { key = "@", mods = "SHIFT|CTRL", action = action.ActivateTab(1) },
        { key = "C", mods = "CTRL", action = action.CopyTo("Clipboard") },
        { key = "C", mods = "SHIFT|CTRL", action = action.CopyTo("Clipboard") },
        { key = "F", mods = "CTRL", action = action.Search("CurrentSelectionOrEmptyString") },
        { key = "F", mods = "SHIFT|CTRL", action = action.Search("CurrentSelectionOrEmptyString") },
        { key = "K", mods = "CTRL", action = action.ClearScrollback("ScrollbackOnly") },
        { key = "K", mods = "SHIFT|CTRL", action = action.ClearScrollback("ScrollbackOnly") },
        { key = "L", mods = "CTRL", action = action.ShowDebugOverlay },
        { key = "L", mods = "SHIFT|CTRL", action = action.ShowDebugOverlay },
        { key = "M", mods = "CTRL", action = action.Hide },
        { key = "M", mods = "SHIFT|CTRL", action = action.Hide },
        { key = "N", mods = "CTRL", action = action.SpawnWindow },
        { key = "N", mods = "SHIFT|CTRL", action = action.SpawnWindow },
        { key = "P", mods = "CTRL", action = action.ActivateCommandPalette },
        { key = "P", mods = "SHIFT|CTRL", action = action.ActivateCommandPalette },
        { key = "R", mods = "CTRL", action = action.ReloadConfiguration },
        { key = "R", mods = "SHIFT|CTRL", action = action.ReloadConfiguration },
        { key = "T", mods = "CTRL", action = action.SpawnTab("CurrentPaneDomain") },
        { key = "T", mods = "SHIFT|CTRL", action = action.SpawnTab("CurrentPaneDomain") },
        {
            key = "U",
            mods = "CTRL",
            action = action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
        },
        {
            key = "U",
            mods = "SHIFT|CTRL",
            action = action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
        },
        { key = "V", mods = "CTRL", action = action.PasteFrom("Clipboard") },
        { key = "V", mods = "SHIFT|CTRL", action = action.PasteFrom("Clipboard") },
        { key = "W", mods = "CTRL", action = action.CloseCurrentTab({ confirm = true }) },
        { key = "W", mods = "SHIFT|CTRL", action = action.CloseCurrentTab({ confirm = true }) },
        { key = "X", mods = "CTRL", action = action.ActivateCopyMode },
        { key = "X", mods = "SHIFT|CTRL", action = action.ActivateCopyMode },
        { key = "Z", mods = "CTRL", action = action.TogglePaneZoomState },
        { key = "Z", mods = "SHIFT|CTRL", action = action.TogglePaneZoomState },
        { key = "[", mods = "SHIFT|SUPER", action = action.ActivateTabRelative(-1) },
        -- LEADER + \\ でPANEを縦方向に開く
        -- | は入力がうまくいかないのでバックスラッシュのキーに置き換える
        { key = "\\", mods = "LEADER", action = action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
        { key = "]", mods = "SHIFT|SUPER", action = action.ActivateTabRelative(1) },
        { key = "^", mods = "CTRL", action = action.ActivateTab(5) },
        { key = "^", mods = "SHIFT|CTRL", action = action.ActivateTab(5) },
        { key = "_", mods = "CTRL", action = action.DecreaseFontSize },
        { key = "_", mods = "SHIFT|CTRL", action = action.DecreaseFontSize },
        { key = "c", mods = "SHIFT|CTRL", action = action.CopyTo("Clipboard") },
        { key = "c", mods = "SUPER", action = action.CopyTo("Clipboard") },
        { key = "f", mods = "SHIFT|CTRL", action = action.Search("CurrentSelectionOrEmptyString") },
        { key = "f", mods = "SUPER", action = action.Search("CurrentSelectionOrEmptyString") },
        -- ALT + hjklでペインの幅を調整する
        { key = "h", mods = "ALT", action = action.AdjustPaneSize({ "Left", 5 }) },
        -- LEADER + hjklでPANEを移動する
        { key = "h", mods = "LEADER", action = action.ActivatePaneDirection("Left") },
        -- ALT + hjklでペインの幅を調整する
        { key = "j", mods = "ALT", action = action.AdjustPaneSize({ "Down", 5 }) },
        -- LEADER + hjklでPANEを移動する
        { key = "j", mods = "LEADER", action = action.ActivatePaneDirection("Down") },
        -- ALT + hjklでペインの幅を調整する
        { key = "k", mods = "ALT", action = action.AdjustPaneSize({ "Up", 5 }) },
        { key = "k", mods = "SHIFT|CTRL", action = action.ClearScrollback("ScrollbackOnly") },
        { key = "k", mods = "SUPER", action = action.ClearScrollback("ScrollbackOnly") },
        -- LEADER + hjklでPANEを移動する
        { key = "k", mods = "LEADER", action = action.ActivatePaneDirection("Up") },
        -- ALT + hjklでペインの幅を調整する
        { key = "l", mods = "ALT", action = action.AdjustPaneSize({ "Right", 5 }) },
        { key = "l", mods = "SHIFT|CTRL", action = action.ShowDebugOverlay },
        -- LEADER + hjklでPANEを移動する
        { key = "l", mods = "LEADER", action = action.ActivatePaneDirection("Right") },
        { key = "m", mods = "SHIFT|CTRL", action = action.Hide },
        { key = "m", mods = "SUPER", action = action.Hide },
        -- LEADER + mでLauncher Menuを開く
        { key = "m", mods = "LEADER", action = action.ShowLauncher },
        { key = "n", mods = "SHIFT|CTRL", action = action.SpawnWindow },
        { key = "n", mods = "SUPER", action = action.SpawnWindow },
        { key = "p", mods = "SHIFT|CTRL", action = action.ActivateCommandPalette },
        { key = "r", mods = "SHIFT|CTRL", action = action.ReloadConfiguration },
        { key = "r", mods = "SUPER", action = action.ReloadConfiguration },
        { key = "t", mods = "SHIFT|CTRL", action = action.SpawnTab("CurrentPaneDomain") },
        { key = "t", mods = "SUPER", action = action.SpawnTab("CurrentPaneDomain") },
        -- LEADER + tでタブを新規作成
        { key = "t", mods = "LEADER", action = action.SpawnTab("CurrentPaneDomain") },
        {
            key = "u",
            mods = "SHIFT|CTRL",
            action = action.CharSelect({ copy_on_select = true, copy_to = "ClipboardAndPrimarySelection" }),
        },
        { key = "v", mods = "SHIFT|CTRL", action = action.PasteFrom("Clipboard") },
        { key = "v", mods = "SUPER", action = action.PasteFrom("Clipboard") },
        { key = "w", mods = "SHIFT|CTRL", action = action.CloseCurrentTab({ confirm = true }) },
        { key = "w", mods = "SUPER", action = action.CloseCurrentTab({ confirm = true }) },
        -- LEADER + wでタブを閉じる
        { key = "w", mods = "LEADER", action = action.CloseCurrentTab({ confirm = true }) },
        -- ALT + x でPANEを閉じる
        { key = "x", mods = "ALT", action = action.CloseCurrentPane({ confirm = true }) },
        { key = "x", mods = "SHIFT|CTRL", action = action.ActivateCopyMode },
        { key = "z", mods = "SHIFT|CTRL", action = action.TogglePaneZoomState },
        { key = "{", mods = "SUPER", action = action.ActivateTabRelative(-1) },
        { key = "{", mods = "SHIFT|SUPER", action = action.ActivateTabRelative(-1) },
        { key = "}", mods = "SUPER", action = action.ActivateTabRelative(1) },
        { key = "}", mods = "SHIFT|SUPER", action = action.ActivateTabRelative(1) },
        { key = "phys:Space", mods = "SHIFT|CTRL", action = action.QuickSelect },
        { key = "PageUp", mods = "SHIFT", action = action.ScrollByPage(-1) },
        { key = "PageUp", mods = "CTRL", action = action.ActivateTabRelative(-1) },
        { key = "PageUp", mods = "SHIFT|CTRL", action = action.MoveTabRelative(-1) },
        { key = "PageDown", mods = "SHIFT", action = action.ScrollByPage(1) },
        { key = "PageDown", mods = "CTRL", action = action.ActivateTabRelative(1) },
        { key = "PageDown", mods = "SHIFT|CTRL", action = action.MoveTabRelative(1) },
        { key = "LeftArrow", mods = "SHIFT|CTRL", action = action.ActivatePaneDirection("Left") },
        { key = "LeftArrow", mods = "SHIFT|ALT|CTRL", action = action.AdjustPaneSize({ "Left", 1 }) },
        { key = "RightArrow", mods = "SHIFT|CTRL", action = action.ActivatePaneDirection("Right") },
        { key = "RightArrow", mods = "SHIFT|ALT|CTRL", action = action.AdjustPaneSize({ "Right", 1 }) },
        { key = "UpArrow", mods = "SHIFT|CTRL", action = action.ActivatePaneDirection("Up") },
        { key = "UpArrow", mods = "SHIFT|ALT|CTRL", action = action.AdjustPaneSize({ "Up", 1 }) },
        { key = "DownArrow", mods = "SHIFT|CTRL", action = action.ActivatePaneDirection("Down") },
        { key = "DownArrow", mods = "SHIFT|ALT|CTRL", action = action.AdjustPaneSize({ "Down", 1 }) },
        { key = "Insert", mods = "SHIFT", action = action.PasteFrom("PrimarySelection") },
        { key = "Insert", mods = "CTRL", action = action.CopyTo("PrimarySelection") },
        { key = "Copy", mods = "NONE", action = action.CopyTo("Clipboard") },
        { key = "Paste", mods = "NONE", action = action.PasteFrom("Clipboard") },
    },

    key_tables = {
        copy_mode = {
            { key = "Tab", mods = "NONE", action = action.CopyMode("MoveForwardWord") },
            { key = "Tab", mods = "SHIFT", action = action.CopyMode("MoveBackwardWord") },
            { key = "Enter", mods = "NONE", action = action.CopyMode("MoveToStartOfNextLine") },
            { key = "Escape", mods = "NONE", action = action.CopyMode("Close") },
            { key = "Space", mods = "NONE", action = action.CopyMode({ SetSelectionMode = "Cell" }) },
            { key = "$", mods = "NONE", action = action.CopyMode("MoveToEndOfLineContent") },
            { key = "$", mods = "SHIFT", action = action.CopyMode("MoveToEndOfLineContent") },
            { key = ",", mods = "NONE", action = action.CopyMode("JumpReverse") },
            { key = "0", mods = "NONE", action = action.CopyMode("MoveToStartOfLine") },
            { key = ";", mods = "NONE", action = action.CopyMode("JumpAgain") },
            { key = "F", mods = "NONE", action = action.CopyMode({ JumpBackward = { prev_char = false } }) },
            { key = "F", mods = "SHIFT", action = action.CopyMode({ JumpBackward = { prev_char = false } }) },
            { key = "G", mods = "NONE", action = action.CopyMode("MoveToScrollbackBottom") },
            { key = "G", mods = "SHIFT", action = action.CopyMode("MoveToScrollbackBottom") },
            { key = "H", mods = "NONE", action = action.CopyMode("MoveToViewportTop") },
            { key = "H", mods = "SHIFT", action = action.CopyMode("MoveToViewportTop") },
            { key = "L", mods = "NONE", action = action.CopyMode("MoveToViewportBottom") },
            { key = "L", mods = "SHIFT", action = action.CopyMode("MoveToViewportBottom") },
            { key = "M", mods = "NONE", action = action.CopyMode("MoveToViewportMiddle") },
            { key = "M", mods = "SHIFT", action = action.CopyMode("MoveToViewportMiddle") },
            { key = "O", mods = "NONE", action = action.CopyMode("MoveToSelectionOtherEndHoriz") },
            { key = "O", mods = "SHIFT", action = action.CopyMode("MoveToSelectionOtherEndHoriz") },
            { key = "T", mods = "NONE", action = action.CopyMode({ JumpBackward = { prev_char = true } }) },
            { key = "T", mods = "SHIFT", action = action.CopyMode({ JumpBackward = { prev_char = true } }) },
            { key = "V", mods = "NONE", action = action.CopyMode({ SetSelectionMode = "Line" }) },
            { key = "V", mods = "SHIFT", action = action.CopyMode({ SetSelectionMode = "Line" }) },
            { key = "^", mods = "NONE", action = action.CopyMode("MoveToStartOfLineContent") },
            { key = "^", mods = "SHIFT", action = action.CopyMode("MoveToStartOfLineContent") },
            { key = "b", mods = "NONE", action = action.CopyMode("MoveBackwardWord") },
            { key = "b", mods = "ALT", action = action.CopyMode("MoveBackwardWord") },
            { key = "b", mods = "CTRL", action = action.CopyMode("PageUp") },
            { key = "c", mods = "CTRL", action = action.CopyMode("Close") },
            { key = "d", mods = "CTRL", action = action.CopyMode({ MoveByPage = 0.5 }) },
            { key = "e", mods = "NONE", action = action.CopyMode("MoveForwardWordEnd") },
            { key = "f", mods = "NONE", action = action.CopyMode({ JumpForward = { prev_char = false } }) },
            { key = "f", mods = "ALT", action = action.CopyMode("MoveForwardWord") },
            { key = "f", mods = "CTRL", action = action.CopyMode("PageDown") },
            { key = "g", mods = "NONE", action = action.CopyMode("MoveToScrollbackTop") },
            { key = "g", mods = "CTRL", action = action.CopyMode("Close") },
            { key = "h", mods = "NONE", action = action.CopyMode("MoveLeft") },
            { key = "j", mods = "NONE", action = action.CopyMode("MoveDown") },
            { key = "k", mods = "NONE", action = action.CopyMode("MoveUp") },
            { key = "l", mods = "NONE", action = action.CopyMode("MoveRight") },
            { key = "m", mods = "ALT", action = action.CopyMode("MoveToStartOfLineContent") },
            { key = "o", mods = "NONE", action = action.CopyMode("MoveToSelectionOtherEnd") },
            { key = "q", mods = "NONE", action = action.CopyMode("Close") },
            { key = "t", mods = "NONE", action = action.CopyMode({ JumpForward = { prev_char = true } }) },
            { key = "u", mods = "CTRL", action = action.CopyMode({ MoveByPage = -0.5 }) },
            { key = "v", mods = "NONE", action = action.CopyMode({ SetSelectionMode = "Cell" }) },
            { key = "v", mods = "CTRL", action = action.CopyMode({ SetSelectionMode = "Block" }) },
            { key = "w", mods = "NONE", action = action.CopyMode("MoveForwardWord") },
            {
                key = "y",
                mods = "NONE",
                action = action.Multiple({ { CopyTo = "ClipboardAndPrimarySelection" }, { CopyMode = "Close" } }),
            },
            { key = "PageUp", mods = "NONE", action = action.CopyMode("PageUp") },
            { key = "PageDown", mods = "NONE", action = action.CopyMode("PageDown") },
            { key = "End", mods = "NONE", action = action.CopyMode("MoveToEndOfLineContent") },
            { key = "Home", mods = "NONE", action = action.CopyMode("MoveToStartOfLine") },
            { key = "LeftArrow", mods = "NONE", action = action.CopyMode("MoveLeft") },
            { key = "LeftArrow", mods = "ALT", action = action.CopyMode("MoveBackwardWord") },
            { key = "RightArrow", mods = "NONE", action = action.CopyMode("MoveRight") },
            { key = "RightArrow", mods = "ALT", action = action.CopyMode("MoveForwardWord") },
            { key = "UpArrow", mods = "NONE", action = action.CopyMode("MoveUp") },
            { key = "DownArrow", mods = "NONE", action = action.CopyMode("MoveDown") },
        },

        search_mode = {
            { key = "Enter", mods = "NONE", action = action.CopyMode("PriorMatch") },
            { key = "Escape", mods = "NONE", action = action.CopyMode("Close") },
            { key = "n", mods = "CTRL", action = action.CopyMode("NextMatch") },
            { key = "p", mods = "CTRL", action = action.CopyMode("PriorMatch") },
            { key = "r", mods = "CTRL", action = action.CopyMode("CycleMatchType") },
            { key = "u", mods = "CTRL", action = action.CopyMode("ClearPattern") },
            { key = "PageUp", mods = "NONE", action = action.CopyMode("PriorMatchPage") },
            { key = "PageDown", mods = "NONE", action = action.CopyMode("NextMatchPage") },
            { key = "UpArrow", mods = "NONE", action = action.CopyMode("PriorMatch") },
            { key = "DownArrow", mods = "NONE", action = action.CopyMode("NextMatch") },
        },
    },
}
