-- nvim-treesitter config
require("nvim-treesitter.configs").setup({
    highlight = {
        enable = true,
        disable = {},
    },
    ensure_installed = {
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "dockerfile",
        "fish",
        "go",
        "gomod",
        "gowork",
        "help",
        "html",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "ninja",
        "nix",
        "ocaml",
        "ocaml_interface",
        "python",
        "regex",
        "rst",
        "ruby",
        "rust",
        "scss",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
    },
})
