name: Run Stylua

on:
  push:
    branches:
      - master
    paths:
      - "**.lua"
  pull_request:
    paths:
      - "**.lua"

permissions: {}

jobs:
  lint:
    name: Run Stylua
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: we recommend pinning to a specific version in case of formatting changes
          version: latest
          # CLI arguments
          args: --check .
